# Generated by Django 6.0.7 on 2026-07-09 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id_permissao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('recurso', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'db_table': 'permissao',
                'unique_together': {('recurso', 'acao')},
            },
        ),
        migrations.CreateModel(
            name='PerfilPermissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='identity.perfil')),
                ('id_permissao', models.ForeignKey(db_column='id_permissao', on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='identity.permissao')),
            ],
            options={
                'verbose_name': 'Permissão do Perfil',
                'verbose_name_plural': 'Permissões dos Perfis',
                'db_table': 'perfil_permissao',
                'unique_together': {('id_perfil', 'id_permissao')},
            },
        ),
    ]
