# Generated by Django 6.0.7 on 2026-07-27 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_plataforma', models.CharField(default='Jinkoni 2026', max_length=120)),
                ('email_suporte', models.EmailField(blank=True, default='', max_length=254)),
                ('paises_participantes', models.JSONField(blank=True, default=list)),
                ('modo_manutencao', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurações do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'configuracoes_sistema',
            },
        ),
    ]
