# Generated by Django 6.0.7 on 2026-07-09 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeEvento',
            fields=[
                ('id_atividade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('formatos_aceitos', models.JSONField(blank=True, default=list)),
                ('prazo', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'atividade_evento',
            },
        ),
        migrations.CreateModel(
            name='Correcao',
            fields=[
                ('id_correcao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('validado_por_admin', models.BooleanField(default=False)),
                ('corrigido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'correcao',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_arquivo', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entrega',
            },
        ),
    ]
