# Generated by Django 6.0.7 on 2026-07-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('eventos', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeevento',
            name='id_evento',
            field=models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='correcao',
            name='id_avaliador',
            field=models.ForeignKey(blank=True, db_column='id_avaliador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcoes_feitas', to='eventos.inscricao'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='enviado_por',
            field=models.ForeignKey(blank=True, db_column='enviado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_enviadas', to='eventos.inscricao'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='id_atividade',
            field=models.ForeignKey(db_column='id_atividade', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='atividades.atividadeevento'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='grupos.grupo'),
        ),
        migrations.AddField(
            model_name='correcao',
            name='id_entrega',
            field=models.OneToOneField(db_column='id_entrega', on_delete=django.db.models.deletion.CASCADE, related_name='correcao', to='atividades.entrega'),
        ),
    ]
