# Generated by Django 6.0.7 on 2026-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_initial'),
        ('eventos', '0003_evento_choices_unique_inscricao'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadeevento',
            options={'ordering': ['prazo']},
        ),
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['-enviado_em']},
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('em_correcao', 'Em correção'), ('corrigida', 'Corrigida')], default='enviada', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(fields=('id_atividade', 'id_grupo'), name='uniq_entrega_atividade_grupo'),
        ),
    ]
