# Generated by Django 6.0.7 on 2026-07-09 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, db_column='aprovado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='id_evento',
            field=models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
