# Generated by Django 6.0.7 on 2026-07-17 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('inscricoes_abertas', 'Inscrições abertas'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado')], default='planejado', max_length=50),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'id_evento'), name='uniq_inscricao_usuario_evento'),
        ),
    ]
