# Generated by Django 6.0.7 on 2026-07-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_choices_unique_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='max_membros_grupo',
            field=models.PositiveIntegerField(default=5, help_text='Tamanho máximo de cada grupo neste evento (definido pelo admin).'),
        ),
    ]
