# Generated by Django 6.0.7 on 2026-07-09 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('link_whatsapp_grupo', models.CharField(blank=True, max_length=255)),
                ('origem', models.CharField(blank=True, max_length=50)),
                ('formado_algoritmo', models.BooleanField(default=False)),
                ('max_membros', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='eventos.evento')),
                ('id_lider', models.ForeignKey(blank=True, db_column='id_lider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_liderados', to='eventos.inscricao')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_lider', models.BooleanField(default=False)),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='grupos.grupo')),
                ('id_inscricao', models.ForeignKey(db_column='id_inscricao', on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_grupo', to='eventos.inscricao')),
            ],
            options={
                'db_table': 'membro_grupo',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='grupos.grupo')),
                ('id_inscricao', models.ForeignKey(db_column='id_inscricao', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_entrada', to='eventos.inscricao')),
            ],
            options={
                'db_table': 'solicitacao_entrada',
            },
        ),
    ]
