# Generated by Django 6.0.7 on 2026-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_choices_unique_inscricao'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='origem',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('algoritmo', 'Algoritmo')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacaoentrada',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('id_evento', 'nome'), name='uniq_grupo_nome_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('id_evento', 'codigo'), name='uniq_grupo_codigo_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='membrogrupo',
            constraint=models.UniqueConstraint(fields=('id_inscricao',), name='uniq_membro_inscricao'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaoentrada',
            constraint=models.UniqueConstraint(fields=('id_grupo', 'id_inscricao'), name='uniq_solicitacao_grupo_inscricao'),
        ),
    ]
