# Generated by Django 6.0.7 on 2026-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_choices_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='max_membros',
            field=models.IntegerField(default=5),
        ),
    ]
