# Generated by Django 6.0.7 on 2026-07-27 21:10

from django.db import migrations, models


def truncar_nomes_grupos(apps, schema_editor):
    Grupo = apps.get_model('grupos', 'Grupo')
    for grupo in Grupo.objects.all().only('id_grupo', 'nome'):
        if grupo.nome and len(grupo.nome) > 40:
            grupo.nome = grupo.nome[:40]
            grupo.save(update_fields=['nome'])


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_max_membros_default'),
    ]

    operations = [
        migrations.RunPython(truncar_nomes_grupos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
