# Generated by Django 6.0.7 on 2026-07-09 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostagemMural',
            fields=[
                ('id_postagem', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('area', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id_autor', models.ForeignKey(blank=True, db_column='id_autor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postagens', to='eventos.inscricao')),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='eventos.evento')),
                ('id_grupo', models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postagens', to='grupos.grupo')),
            ],
            options={
                'db_table': 'postagem_mural',
            },
        ),
        migrations.CreateModel(
            name='RespostaMural',
            fields=[
                ('id_resposta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_autor', models.ForeignKey(blank=True, db_column='id_autor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='eventos.inscricao')),
                ('id_postagem', models.ForeignKey(db_column='id_postagem', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='mural.postagemmural')),
            ],
            options={
                'db_table': 'resposta_mural',
            },
        ),
    ]
