# Generated by Django 6.0.7 on 2026-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagemmural',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='respostamural',
            options={'ordering': ['criado_em']},
        ),
        migrations.AlterField(
            model_name='postagemmural',
            name='area',
            field=models.CharField(blank=True, choices=[('geral', 'Geral'), ('duvidas', 'Dúvidas'), ('anuncios', 'Anúncios'), ('networking', 'Networking')], default='geral', max_length=100),
        ),
        migrations.AlterField(
            model_name='postagemmural',
            name='status',
            field=models.CharField(choices=[('publicada', 'Publicada'), ('oculta', 'Oculta'), ('arquivada', 'Arquivada')], default='publicada', max_length=50),
        ),
    ]
