# Generated by Django 6.0.7 on 2026-07-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0002_choices_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemmural',
            name='area',
            field=models.CharField(blank=True, choices=[('geral', 'Geral'), ('duvidas', 'Dúvidas'), ('anuncios', 'Anúncios')], default='geral', max_length=100),
        ),
    ]
